### ISSUE TITLE
project_search not respecting platforms, languages, or license

### ISSUE THREAD

**Issue by kikass13** [pybraries/pybraries#182]
Hello, I hope that you can help me finding my problem.

**Describe the bug**
We use the pybraries api in our protontypes/openselery project [[https://github.com/protontypes/openselery](https://github.com/protontypes/openselery)] and once in a while (consistent) we search for some projects, this little 'global-data-manager' fella pops up instead of some proper results (i cannot reproduce this behavior on the normal web page of librariesIo).

Im not really sure what causes this but as I mentioned, this is consistent.
This is my code:
``` python
        from pybraries.search import Search

        project = None
        search = Search()
        results = search.project_search(
            filters={"keywords": depName, "manager": platform}
        )
        # only choose first search result
        if results:
            print(results[0])
            d = results[0]
            print(platform, d)
```

**To Reproduce**
1a. `results = search.project_search(filters={"keywords": "gitpython", "manager": "pypi"})`
2a. results[0] =>> global-data-manager
1b. `results = search.project_search(filters={"keywords": "pybraries", "manager": "pypi"})`
2b. results[0] =>> global-data-manager
1c. `results = search.project_search(filters={"keywords": "urlextract", "manager": "pypi"})`
2c. results[0] =>> global-data-manager

**Expected behavior**
I would expect to see whatever the wegpage of librariesio is searching instead of some random module which has nothing to do with what i searched for.

 - Pybraries Version [e.g. .0.2.2]

**Additional context**

- This is an issue born from protontypes/openselery#98.

- The code Im using can be found here https://github.com/protontypes/openselery/blob/368a993ce132b47490ee26f9e82aa96778804a10/openselery/librariesio_connector.py#L48

Thank you!

**Comment by discdiver** [comment]
Thank you for raising this. Sorry. Just saw this. should be fixed now. The `project_search` pattern in the underlying Libraries.io API is doesn't follow the pattern of all the others.   Version 0.3.0 of Pybraries is not on Pypi. Just make sure you pass 'project_search(keywords='gitpython')` with any other filters or sorts as dictionaries with keyword arguments.

**Comment by discdiver** [comment]
install version 0.3.1 - now the latest version on pypi - and you should be set

**Comment by kikass13** [comment]
@discdiver 
thanks, im gonna try it tomorrow

**Comment by kikass13** [comment]
Here is my code:

```
from pybraries.search import Search

project = None
search = Search()
results = search.project_search(keywords='gitpython', sort='stars', platform='pypi')
# only choose first search result
print(results[0].get("name"))
print(results[0].get("description"))
print(results[0].get("repository_url"))
```

the version 0.3.1 does not work, even without the platform filter.

**Comment by kikass13** [comment]
### update: 

The version 0.3.0 however works as expected and results in the following output:
```
GitPython
Python Git Library
https://github.com/gitpython-developers/GitPython
```

I guess i will stick with the version 0.3.0 for now until you figure out whatever went wrong, thanks however for the effort :+1: 
i mentioned this issue, so you know where my use case results from, have a nice week :)

**Comment by discdiver** [comment]
Thanks. Will try to figure out what's up this weekend.

**Comment by discdiver** [comment]
alright 0.3.4 should do the trick. works fine when I test with your use case.
