### ISSUE TITLE
It's lie

### ISSUE THREAD

**Issue by weerdy15** [pybraries/pybraries#219]
In the project's README said that

> All libraries.io methods are implemented, except updating a subscription to not include prereleases.

but this is an absolute lie. The libraries.io's API have platforms, repositories, projects, and even users, while this library weakly covers only search and subscriptions (and even not completely). I disagree with how the project positioning itself.

**Comment by discdiver** [comment]
All those methods are available via Search or Subscribe methods. Are those not working for you? 

See the docs here: 
https://pybraries.readthedocs.io/en/latest/stubs/pybraries.search.Search.html

**Comment by weerdy15** [comment]
Oh, my fail. Much sorry for this situation! It wasn't obvious to me. Sorry again!
